### PR TITLE
Bump to Kubernetes 1.9.2

### PR DESCRIPTION
**Pull request by errordeveloper**
@ijc PTAL

### CODE REVIEW

**Comment by ijc** [comment]
You need to run `make update-hashes` to fix the CI. Unlike the main repo you can update hashes in the same commit as you change things.

**Comment by ijc** [comment]
What is the failure? Perhaps we can come up with a more portable rune?

**Comment by errordeveloper** [comment]
```
> make update-hashes
set -e ; for tag in $(linuxkit pkg show-tag pkg/kubelet) \
	           $(linuxkit pkg show-tag pkg/cri-containerd) \
	           $(linuxkit pkg show-tag pkg/kubernetes-docker-image-cache-common) \
	           $(linuxkit pkg show-tag pkg/kubernetes-docker-image-cache-control-plane) ; do \
	    image=${tag%:*} ; \
	    git grep -E -l "\b$image:" | xargs --no-run-if-empty sed -i.bak -e "s,$image:[[:xdigit:]]\{40\}\(-dirty\)\?,$tag,g" ; \
	done
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
make: *** [update-hashes] Error 1
```

**Comment by errordeveloper** [comment]
@ijc this PR should be good to go, let's discuss the portability of `make update-hashes` in https://github.com/linuxkit/kubernetes/issues/52.

**Pull request merged**
