### PR TITLE
Use alexellis/derek bot to manage PRs and issues

### PR DESCRIPTION
**Pull request by tiborvass**
**- What I did**
Added support for @alexellis's derek bot, which extends Github's user permissions to help non-committers to manage issues and pull requests simply by commenting.
More information on https://github.com/alexellis/derek#derek

**- How I did it**
Added a .DEREK file and updated CONTRIBUTING.md

**- How to verify it**

**- Description for the changelog**
Experiment using alexellis/derek bot to manage PRs and issues

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by alexellis** [comment]
This is part of a wider discussion with @thaJeztah and @justincormack. More info on bot commands:

https://github.com/alexellis/derek#what-can-i-do

**Comment by ijc** [comment]
Discussion elsewhere isn't really good enough I'm afraid.

The PR should be self-contained/describing. In repo docs are required so it can be used in the future without having to dig out this PR.

**Comment by tiborvass** [comment]
@ijc you're right, I'll update the PR accordingly.

**Comment by tiborvass** [comment]
@ijc sorry for the delay, I updated the CONTRIBUTING guide. We'd like to try out this tool and thought it would be good to try on this repo.

**Comment by alexellis** [comment]
Thanks for updating Tibor. If you guys need more background info let me know.

**Comment by alexellis** [comment]
@ijc how does this look now?

**Comment by tiborvass** [comment]
@ijc @justincormack @rn @deitch @riyazdf PTAL

**Comment by rn** [comment]
I don't quite see what problem this solves for us. We already have poule/gordon for DCO checking and the project is smallish enough to manage maintainers via GH permissions.

**Comment by ijc** [comment]
I don't see the utility personally either, it seems to be solving some problem with this repo doesn't have in practice today, so enabling it here isn't going to gain us much useful exposure to the tool, if that is the aim. Especially since everyone on the whitelist already has credentials to do everything the tool does.

**Comment by tiborvass** [comment]
Fair points. Thanks guys for your input :)

**Comment by alexellis** [comment]
We have it deployed on moby/moby now where it makes more sense due to presence of external contributors. Thanks for entertaining the request.

**Pull request closed without merging**
