### PR TITLE
update metadata parameter

### PR DESCRIPTION
**Pull request by w9n**
due to linuxkit/linuxkit#2861

### CODE REVIEW

**Comment by deitch** [comment]
The new syntax only is necessary (and required) with an `lkt` image built with the new metadata. Don't you need to update the hash [here](https://github.com/linuxkit/kubernetes/blob/f7ac0ba64af4d14a3ac46433daa24b4b3be80ced/yml/kube.yml#L20) at the same time?

**Comment by w9n** [comment]
its a parameter of the linuxkit cli and should have nothing to do with the metadata pkg. I didnt test linuxkit/linuxkit#2864 (unrelated to this).

**Comment by ijc** [comment]
This change is correct but please could you also update `.circleci/config.yml` to pull in the current master build of linuxkit (from linuxkit/linuxkit's CI, i.e. bump the URL and the sha256). `linuxkit run` isn't used in this repo but leaving them out of sync will just confuse someone later on.

**Comment by deitch** [comment]
> its a parameter of the linuxkit cli and should have nothing to do with the metadata pkg

You are right. I confused the cli change from earlier this week with the pkg change from earlier this week. Never mind.

**Comment by w9n** [comment]
@ijc sure, but please give me the URL of the latest artifact or some location where i can see a list of them.

**Comment by ijc** [comment]
Can you see https://circleci.com/gh/linuxkit/linuxkit/501#artifacts/containers/0 ? 

Reached from https://circleci.com/gh/linuxkit/linuxkit , choose the latest master (501 right now) which takes to https://circleci.com/gh/linuxkit/linuxkit/501 and then there is an "Artifacts" tab.

**Comment by w9n** [comment]
thanks, I can see all of it but couldnt figure it out from `.circleci/config`. Should be good now.

**Comment by ijc** [comment]
Perhaps we should add a comment just above the curl of linuxkit binary, something like;
```
# To update find the most recent successful build at https://circleci.com/gh/linuxkit/linuxkit/tree/master
# and find the link + SHA256 in the `Artifacts` tab
```
? If you agree would you mind adding it here too.

**Comment by w9n** [comment]
makes sense, the first failure was due to the registry having a bad day today, had this random failures a couple of times today.

**Pull request merged**
