### PR TITLE
move moby config from Dockerfile to build.yml

### PR DESCRIPTION
**Pull request by w9n**
**- What I did**
used  linuxkit/linuxkit#2777
**- How I did it**
https://www.json2yaml.com/
**- How to verify it**
build the package.
**- Description for the changelog**
move moby config from Dockerfile to build.yml

**- A picture of a cute animal (not mandatory but encouraged)**
rainbow dog

### CODE REVIEW

**Comment by ijc** [comment]
BTW I've also just managed to figure out why my local patches to allow this label to be moved into the `build.yml` consumed by `linuxit pkg build` as actual structured yaml wasn't working -- I'm hoping to raise that as a PR shortly. That would make this change somewhat moot, but no harm in doing this for now while I shepherd that change through.

**Comment by ijc** [comment]
> I'm hoping to raise that as a PR shortly. 

See: https://github.com/linuxkit/linuxkit/pull/2777

**Comment by w9n** [comment]
good solution. I will change the PR appropriately.

**Comment by w9n** [comment]
ive updated the PR, works like a charm on your branch!

**Comment by ijc** [comment]
Please add a commit to the _start_ of your branch to switch `.circleci/config.yml` to download the `linuxkit` binary from https://215-46932243-gh.circle-artifacts.com/0/linuxkit-linux-amd64 and update the sha256 to 1f39537da2b83fa618cbba110ede937fa7b34577026cf1369d280fd372c8efc1.

If that is a problem let me know and I will make a PR doing just the bump for you to rebase on.

**Comment by w9n** [comment]
no problem, done and passed.

**Comment by ijc** [comment]
Actually, the image caches do not get pushed by the new CI, so please do the hash update (all of them) in a separate commit at the end only.

**Comment by w9n** [comment]
weird... something must gone wrong on rebasing - should be fine now :/

**Pull request merged**
